### ISSUE TITLE
Remove more outdated styles

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/modern-normalize#1]
I've already removed a lot of outdated styles (https://github.com/sindresorhus/modern-normalize/commit/c2e7aa3009b2a2391fabca66326a88bbffd16acf https://github.com/sindresorhus/modern-normalize/commit/b52144d04b756539ac5ac8734213ed812f349d2a), but I'm sure there are more things that are fixed in browsers by now. We should go through the styles and check whether they're still valid in latest Chrome and Firefox.

**Comment by ismamz** [comment]
Hi @sindresorhus! Are you just testing in the last version of Chrome and the last version of Firefox?

**Comment by sindresorhus** [comment]
Yes

**Comment by ismamz** [comment]
Ok. So, the `h1` rule is outdated.

![ua](https://user-images.githubusercontent.com/3452011/35985009-631e7fe8-0cd4-11e8-8900-588a2d03965b.jpg)

I can send a pull request if you wish.

**Comment by ismamz** [comment]
The `h1` element has the same behavior in both browsers (within `article` or `section` too). So, the [rule here](https://github.com/sindresorhus/modern-normalize/blob/master/modern-normalize.css#L39) it should not be necessary if you are "normalizing", otherwise it should be indicated as "opinionated".
Are you agree?

**Comment by sindresorhus** [comment]
@ismamz Try using `git blame` to see when it was introduced and why. There might be something you're missing. https://github.com/necolas/normalize.css/blame/master/normalize.css

**Comment by ismamz** [comment]
@sindresorhus Sorry, but I don't find the reason to keep this rule. Maybe I missing something. I did a test and there are no difference when you write `h1` withing nested HTML sections (`section`, `aside`, etc). By the way, a HTML test file could be useful.

**Comment by sindresorhus** [comment]
These are the relevant commits: https://github.com/necolas/normalize.css/commit/e9e28741f4032be46063c5afa62ad2efc8d8f911 https://github.com/necolas/normalize.css/commit/fc85cfb9f16200b4fa048b73c34e295dc77487d1

**Comment by charakterziffer** [comment]
I’m pretty sure the smaller h1 is a feature, not a bug. Since HTML5 it’s possible, to ignore the “correct” header nesting, use only h1 and signal the subordination with nested sections or articles, see https://stackoverflow.com/questions/24986162/html5-nested-sections-and-heading-tags/24987792#24987792

Yes, browser may interpret this different, but if you resize the nested h1 back to it’s original size you prevent this possibility HTML5 offers. It would be more correct to enable this smaller sectioned headings in all browsers, but because it depends heavily on the whole context, that may be difficult to do with normalize.css.

**Comment by ismamz** [comment]
@charakterziffer I agree that it is a feature. How modern-normalize does not support IE and other older browsers that might have trouble with this, there is no need to support them. There is no reason to keep it in modern-normalize.css (it does not normalize), and perhaps it can be useful in modern-base.css.

Here is a related issue: #23
