### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by paulirish** [sindresorhus/modern-normalize#15]
Are any versions of IE supported or just Edge?

**Comment by sindresorhus** [comment]
Latest Chrome, Firefox, Safari. IE is not supported for obvious reasons. Edge is not supported because of tiny market share and by principle, I'm not interested in spending my open source time on a closed-source browser.

**Comment by Zirro** [comment]
@rgfx If you still need support for Internet Explorer, why not use the original normalize.css? There wouldn't be much of a difference between this package and the original if it still had to include all the IE-specific rules. The point of this package - as implied by the name - is to support modern browsers.

**Comment by rgfx** [comment]
Yeah, that's a good point. I struggle to find a good use case for not supporting IE. I was hoping that your normalizer would support modern IE.

**Comment by Zirro** [comment]
> ...your normalizer...

Just in case, as I feel obliged to clear up potential misunderstandings - I've only made one contribution to this project so far, and don't want to speak for Sindre. That said, he explained his intended use cases for modern-normalize like so:

> [Any personal project, Electron apps, and some clients.](https://www.designernews.co/comments/283704)

I have a few private projects with similar requirements as well.

<details><summary>Perhaps not quite as relevant, but...</summary>I also work on a site in the Alexa Top 10k, where less than 1% of our visitors are using Internet Explorer. I'm pretty sure I've been the only developer who's actively tested and fixed things in IE11 for the last two years, but now even I am tempted to switch to modern-normalize in order to hasten the demise of a browser which will not receive any further updates.</details>

**Comment by rgfx** [comment]
Good to know about that 1% figure. Please let the demise come soon. Thanks for taking the time to tell me your thoughts on the matter, truly appreciated.
