### ISSUE TITLE
Use `system-ui` in the default font stack

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/modern-normalize#18]
It was not included in the initial PR, as per [this blog post](http://markdotto.com/2018/02/07/github-system-fonts/), it's not yet safe to use. We need to move on soon though, as Chrome plans to deprecate the `BlinkMacSystemFont` font name, per https://github.com/sindresorhus/modern-normalize/pull/16#issuecomment-364504396.

Also see: https://github.com/primer/primer/pull/408

**Comment by jonathantneal** [comment]
@broccolini, @mdo, has the `system-ui` issue been resolved, or if not, might placing `system-ui` behind `-apple-system` in the font stack resolve the i18n issues?

---

For others interested in this issue and also when and why things changed over the years, I’ve put together a little history of the popular system font stack:

### 2016

- In early 2016, [the first system font family stack was added](https://github.com/twbs/bootstrap/commit/73e5e89e0efb938072ba3b1da5d06d0d0e659db9) to Bootstrap. Later that day, [Open Sans was removed and Fira and Droid Sans were added](https://github.com/twbs/bootstrap/commit/cd3af1fa1ae71529e377c68f7a29d37c5d5bd051) (presumably the former to only use native fonts, and the later for FirefoxOS and Android compatibility).

- A few months later, [system-ui was removed](https://github.com/twbs/bootstrap/commit/c6168b64ed32a4787365d03a5fa65de157799452) for i18n issues. @mdo wrote about it [here](http://markdotto.com/2018/02/07/github-system-fonts/), and the gist was:

  > [Our users] were quick to point out to our Support teams that the new `system-ui` alias caused issues in WebKit and Blink browsers with non-English languages.

- A few months later, [Oxygen, Ubuntu, Cantarell, Fira Sans, and Droid Sans font families were removed](https://github.com/twbs/bootstrap/commit/0a31dacf3e0c43a73b2e61e266155b9dcce35339) for being too varied in their appearance.

  @mdo wrote more about it [here](https://github.com/primer/primer/pull/408#issuecomment-349421942) and [here](http://markdotto.com/2018/02/07/github-system-fonts/), and the gist was:

  > Linux users were the most upset at the change given Linux system fonts seem to be rather large and clunky, and their system fonts so inconsistent across distros.

  Note that while Roboto was removed from GitHub’s CSS, it was not removed from Bootstrap.

  > We ended up removing Roboto because it caused issues in some distros of Linux. We definitely need to revisit it.

  Also, note that while the post mentions sneaking `SF Mono` into the stack, which is also recommended in various font stacks on the internet, `SF Mono` is not an “official” system font in the installed sense. You cannot use it outside of Terminal, Console, or Xcode without a manual installation. Also, it does not appear to be currently shipping in GitHub’s CSS.

### 2017

- A year later, in 2017, things remained settled, and [Emojis were added](https://github.com/twbs/bootstrap/commit/4634b39a1bd2034a5d6d9c3ba9872905580c4a39).

### 2018

- And another year later, [Noto Color Emoji was added for Linux compatibility](https://github.com/twbs/bootstrap/commit/4634b39a1bd2034a5d6d9c3ba9872905580c4a39).

---

So, it seems like roughly two years have passed since the initial `system-ui` bug was worked around, and possibly a year since it was last looked into.
